files: always attempt t to track installed configuration files, even if not automerging

diff --git a/mk/pkginstall/files b/mk/pkginstall/files
--- a/mk/pkginstall/files
+++ b/mk/pkginstall/files
@@ -187,106 +187,119 @@ ADD)
 				fi
 				if ${TEST} -f "$file"; then
 					${ECHO} "${PKGNAME}: $file already exists"
-					if ${TEST} "$_VCS_ENABLED" = "yes" -o "$_VCS_ENABLED" = "YES" && ! ${ECHO} "$f_flags" | ${GREP} -Fq "r" && ${TEST}"$VCSAUTOMERGE" = "yes" -a ! "$VCSCONFPULL" = "yes"; then
-						${ECHO} "${PKGNAME}: attempting to merge $file with new defaults!"
-						merge_userinstalled() {
-							${ECHO} "Saving the currently user-installed revision to $_VCSDIR/user/$file"
-							${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null
-							${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null
-							${CP} -fp "$file" "$_VCSDIR/user/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING REGISTER "$_VCSDIR/user/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING COMMIT "backup user conf before attempting merge for $PKGNAME"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
-							${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
-							mergestatus=$?
-							case $mergestatus in
-							0)
-								${ECHO} "Merged with no conflicts. installing it to $file!"
-								${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
-								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
-								if ${TEST} $? -eq 0; then
-									${ECHO} "$file" >> "$_VCSDIR/automergedfiles"
-									${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
-									${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
-									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
-									${TEST} ! -x ./+VERSIONING ||
-										./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
-								fi
+					if ${TEST} "$_VCS_ENABLED" = "yes" -o "$_VCS_ENABLED" = "YES" -a ! ! "$VCSCONFPULL" = "yes" && ! ${ECHO} "$f_flags" | ${GREP} -Fq "r"; then
+						if ${TEST} "$VCSAUTOMERGE" = "yes" -o "$VCSAUTOMERGE" = "YES"; then
+							${ECHO} "${PKGNAME}: attempting to merge $file with new defaults!"
+							merge_userinstalled() {
+								${ECHO} "Saving the currently user-installed revision to $_VCSDIR/user/$file"
+								${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null
+								${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null
+								${CP} -fp "$file" "$_VCSDIR/user/$file"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
-								${ECHO} "Revert from the last revision of $_VCSDIR/user/$file if needed"
-								;;
-							1)
-								${ECHO} "Some conflicts merging. manually review them in"
-								${ECHO} "$_VCSDIR/defaults/$file.automerge"
-								${ECHO} "then copy the result to $file"
-								;;
-							*)
-								${ECHO} "Merge exited with errors. not changing anything"
-								;;
-							esac
-						}
-						merge_automerged () {
-							${ECHO} "Saving the currently installed revision to $_VCSDIR/automerged/$file"
-							${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
-							${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
-							${CP} -fp "$file" "$_VCSDIR/automerged/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING COMMIT "backup preexisting conf before attempting merge for $PKGNAME"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
-							${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
-							mergestatus=$?
-							case $mergestatus in
-							0)
-								${ECHO} "Merged with no conflict. installing it to $file!"
-								${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
-								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
-								${TEST} -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
-								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
-								${TEST} -x ./+VERSIONING ||
+									./+VERSIONING REGISTER "$_VCSDIR/user/$file"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING COMMIT "backup user conf before attempting merge for $PKGNAME"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
+								${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
+								mergestatus=$?
+								case $mergestatus in
+								0)
+									${ECHO} "Merged with no conflicts. installing it to $file!"
+									${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
+									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+									if ${TEST} $? -eq 0; then
+										${ECHO} "$file" >> "$_VCSDIR/automergedfiles"
+										${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
+										${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
+										${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+										${TEST} ! -x ./+VERSIONING ||
+											./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
+									fi
+									${TEST} ! -x ./+VERSIONING ||
+										./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
+									${ECHO} "Revert from the last revision of $_VCSDIR/user/$file if needed"
+									;;
+								1)
+									${ECHO} "Some conflicts merging. manually review them in"
+									${ECHO} "$_VCSDIR/defaults/$file.automerge"
+									${ECHO} "then copy the result to $file"
+									;;
+								*)
+									${ECHO} "Merge exited with errors. not changing anything"
+									;;
+								esac
+							}
+							merge_automerged () {
+								${ECHO} "Saving the currently installed revision to $_VCSDIR/automerged/$file"
+								${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
+								${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
+								${CP} -fp "$file" "$_VCSDIR/automerged/$file"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING COMMIT "backup preexisting conf before attempting merge for $PKGNAME"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
+								${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
+								mergestatus=$?
+								case $mergestatus in
+								0)
+									${ECHO} "Merged with no conflict. installing it to $file!"
+									${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
+									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+									${TEST} -x ./+VERSIONING ||
+										./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
+									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+									${TEST} -x ./+VERSIONING ||
+										./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
+									${ECHO} "Revert from the penultimate revision of $_VCSDIR/automerged/$file if needed"
+									;;
+								1)
+									${ECHO} "Some conflicts merging. manually review them in"
+									${ECHO} "$_VCSDIR/defaults/$file.automerge"
+									${ECHO} "then copy the result to $file"
+									;;
+								*)
+									${ECHO} "Merge exited with errors. not changing anything"
+									;;
+								esac
+							}
+							if ${TEST} -f "$_VCSDIR/automergedfiles" && ${GREP} -Fq "$file" "$_VCSDIR/automergedfiles"; then
+								#check if the automergedfile was manually edited after being automatically registered as merged
+								${TEST} ! -x ./+VERSIONING ||
 									./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
-								${ECHO} "Revert from the penultimate revision of $_VCSDIR/automerged/$file if needed"
-								;;
-							1)
-								${ECHO} "Some conflicts merging. manually review them in"
-								${ECHO} "$_VCSDIR/defaults/$file.automerge"
-								${ECHO} "then copy the result to $file"
-								;;
-							*)
-								${ECHO} "Merge exited with errors. not changing anything"
-								;;
-							esac
-						}
-						if ${TEST} -f "$_VCSDIR/automergedfiles" && ${GREP} -Fq "$file" "$_VCSDIR/automergedfiles"; then
-							#check if the automergedfile was manually edited after being automatically registered as merged
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
-							if ${TEST} -f "$_VCSDIR/automerged/$file"; then
-								${DIFF} -q "$file" "$_VCSDIR/automerged/$file" 2>/dev/null
-								if ${TEST} ! $? -eq 0; then
-									#the installed file and the last automerged version differ! must have been manually edited after being committed
-									${GREP} -Fv "$file" "$_VCSDIR/automergedfiles" > "$_VCSDIR/automergedfiles.rm"
-									${MV} -f "$_VCSDIR/automergedfiles.rm" "$_VCSDIR/automergedfiles"
-									merge_userinstalled
+								if ${TEST} -f "$_VCSDIR/automerged/$file"; then
+									${DIFF} -q "$file" "$_VCSDIR/automerged/$file" 2>/dev/null
+									if ${TEST} ! $? -eq 0; then
+										#the installed file and the last automerged version differ! must have been manually edited after being committed
+										${GREP} -Fv "$file" "$_VCSDIR/automergedfiles" > "$_VCSDIR/automergedfiles.rm"
+										${MV} -f "$_VCSDIR/automergedfiles.rm" "$_VCSDIR/automergedfiles"
+										merge_userinstalled
+									else
+										merge_automerged
+									fi
 								else
 									merge_automerged
 								fi
 							else
-								merge_automerged
+								merge_userinstalled
 							fi
 						else
-							merge_userinstalled
+						#always track installed conf files
+							if ! ${GREP} -Fq "$file" "$_VCSDIR/automergedfiles" 2>/dev/null; then
+								${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null;
+								${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null;
+								${CP} -fp "$file" "$_VCSDIR/user/$file";
+								if ${TEST} $? -eq 0; then
+									${ECHO} "Attempting to track the existing configuration file"
+									${TEST} ! -x ./+VERSIONING ||
+										./+VERSIONING REGISTER "$_VCSDIR/user/$file"
+								fi
 						fi
 					fi
 				elif ${TEST} -f "$f_eg" -o -c "$f_eg" && ${TEST} "$_VCSCONFPULLFAIL" = "yes" -o ! "$VCSCONFPULL" = "yes" || ${ECHO} "$f_flags" | ${GREP} -Fq "r"; then
