check for mergedfiles existance, avoid printing missing file errors

diff --git a/mk/pkginstall/files b/mk/pkginstall/files
--- a/mk/pkginstall/files
+++ b/mk/pkginstall/files
@@ -167,8 +167,7 @@ ADD)
 					${ECHO} "${PKGNAME}: $file already exists"
 					if ${TEST} ! -n "$NOVCS" -a "$VCSAUTOMERGE" = "yes"; then
 						${ECHO} "${PKGNAME}: attempting to merge $file with new defaults!"
-						alreadyautomerged=$(${GREP} -c "$file" "$_VCSDIR/automergedfiles")
-						if ${TEST} "$alreadyautomerged" -gt 0; then
+						if ${TEST} -f "$_VCSDIR/automergedfiles" -a $(${GREP} -c "$file" "$_VCSDIR/automergedfiles") -gt 0; then
 							${ECHO} "saving the currently installed revision to $_VCSDIR/automerged/$file"
 							${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
 							${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
@@ -178,23 +177,23 @@ ADD)
 							${RM} -f "$_VCSDIR/defaults/$file.automerge" 2>/dev/null
 							${TEST} ! -x ./+VERSIONING ||
 								./+VERSIONING MERGE "_VCSDIR/defaults/$file" "$file" 	
-								mergestatus=$?
-								case $mergestatus in
-								0)
-									${ECHO} "merged with no conflict. installing it to $file!"
-									${DIFF} -uq "$file" "$_VCSDIR/defaults/$file.automerge"
-									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
-									${ECHO} "revert from the last revision of $_VCSDIR/automerged/$file if needed"
-									;;
-								1)
-									${ECHO} "some conflicts merging. manually review them in"
-									${ECHO} "$_VCSDIR/defaults/$file.automerge"
-									${ECHO} "then copy the result to $file"
-									;;
-								*)
-									${ECHO} "merge exited with errors. not changing anything"		
-									;;
-								esac	
+							mergestatus=$?
+							case $mergestatus in
+							0)
+								${ECHO} "merged with no conflict. installing it to $file!"
+								${DIFF} -uq "$file" "$_VCSDIR/defaults/$file.automerge"
+								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+								${ECHO} "revert from the last revision of $_VCSDIR/automerged/$file if needed"
+								;;
+							1)
+								${ECHO} "some conflicts merging. manually review them in"
+								${ECHO} "$_VCSDIR/defaults/$file.automerge"
+								${ECHO} "then copy the result to $file"
+								;;
+							*)
+								${ECHO} "merge exited with errors. not changing anything"		
+								;;
+							esac
 						else
 							${ECHO} "saving the currently user-installed revision to $_VCSDIR/user/$file"
 							${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null
