review: try to apply suggestions made by roland.illig@gmx.de, and target solaris

diff --git a/mk/pkginstall/files b/mk/pkginstall/files
--- a/mk/pkginstall/files
+++ b/mk/pkginstall/files
@@ -53,6 +53,7 @@ CHGRP="@CHGRP@"
 CHMOD="@CHMOD@"
 CHOWN="@CHOWN@"
 CMP="@CMP@"
+DIFF="@DIFF@"
 ECHO="@ECHO@"
 GREP="@GREP@"
 LS="@LS@"
@@ -65,11 +66,9 @@ SED="@SED@"
 SORT="@SORT@"
 TEST="@TEST@"
 TRUE="@TRUE@"
-DIFF="@DIFF@"
 
 SELF=$0
 ACTION=$1
-
 : ${PKG_PREFIX=@PREFIX@}
 
 case "${PKG_CONFIG:-@PKG_CONFIG@}" in
@@ -104,7 +103,7 @@ PKG_METADATA_DIR="${2-${CURDIR}}"
 PKG_REFCOUNT_FILES_DBDIR="${PKG_REFCOUNT_DBDIR}/files"
 _VCSCONFPULLFAIL=$3
 _VCSDIR="${VCSDIR:-@VARBASE@/confrepo}"
-_VCS_ENABLED="${VCS_CONF_FILES:-no}"
+_VCS_ENABLED="${VCSTRACK_CONF:-no}"
 case "${_VCS_ENABLED}" in
 [Nn][Oo])
 	_VCS_ENABLED=no
@@ -165,17 +164,20 @@ ADD)
 		"")	;;
 	 	*)	${ECHO} "$f_mode $f_user $f_group" > $perms ;;
 		esac
-		if ${TEST} ! -f "$file" -a ! -f "$f_eg" -a ! -c "$f_eg"; then
+
+		if ${TEST} ! -f "$file" \
+		&& ${TEST} ! -f "$f_eg" \
+		&& ${TEST} ! -c "$f_eg"; then
 			:
 		else
 			case "$f_flags:$_PKG_CONFIG:$_PKG_RCD_SCRIPTS" in
 			*f*:*:*|[!r]:yes:*|[!r][!r]:yes:*|[!r][!r][!r]:yes:*|*r*:yes:yes)
 				if ${TEST} "${_VCS_ENABLED}" = "yes" \
-				&& ! ${ECHO} "${f_flags}" | grep -Fq "r" \
-				&& ${TEST} ! "${VCSCONFPULL}" = "yes"; then
+				&& ${TEST} "${f_flags%r*}" = "${f_flags}" \
+				&& ${TEST} "${VCSCONFPULL}" != "yes"; then
 					if ${TEST} ! -d "${_VCSDIR}"; then
 						${MKDIR} -p "${_VCSDIR}"
-						if ${TEST} ! $? -eq 0; then
+						if ${TEST} $? -ne 0; then
 							_VCS_ENABLED=no
 						fi
 					fi
@@ -194,9 +196,9 @@ ADD)
 					done
 					${TEST} ! -x ./+VERSIONING ||
 						./+VERSIONING PREPARE
-					if ${TEST} ! $? -eq 0; then
-						${ECHO} "Failed to initialize the repository that should store configuration revisions at ${_VCSDIR}!"
-						${ECHO} "Temporarily disabling configuration files version tracking"
+					if ${TEST} $? -ne 0; then
+						${ECHO} 1>&2 "Failed to initialize the repository that should store configuration revisions at ${_VCSDIR}!"
+						${ECHO} 1>&2 "Temporarily disabling configuration files version tracking"
 						_VCS_ENABLED=no
 					fi
 					if ${TEST} -w "${_VCSDIR}/defaults"; then
@@ -207,17 +209,18 @@ ADD)
 							./+VERSIONING REGISTER "${_VCSDIR}/defaults/${file}" 
 							${ECHO} REGISTER "${_VCSDIR}/defaults/${file}"
 					else
-						${ECHO} "${_VCSDIR} is not writable!"
+						${ECHO} 1>&2 "${_VCSDIR} is not writable!"
 					fi	
 				fi
 				if ${TEST} -f "${file}"; then
 					${ECHO} "${PKGNAME}: ${file} already exists"
 					if ${TEST} "${_VCS_ENABLED}" = "yes" \
-					-a ! "${VCSCONFPULL}" = "yes"\
-					&& ! ${ECHO} "${f_flags}" | ${GREP} -Fq "r"; then
+					&& ${TEST} ! "${VCSCONFPULL}" = "yes"\
+					&& ${TEST} "${f_flags%r*}" = "${f_flags}"; then
 						if ${TEST} "${VCSAUTOMERGE}" = "yes"; then
 							${ECHO} "${PKGNAME}: attempting to merge ${file} with new defaults!"
-							merge_userinstalled() {
+							merge_userinstalled()
+							{
 								${ECHO} "Saving the currently user-installed revision to ${_VCSDIR}/user/${file}"
 								${MKDIR} -p "${_VCSDIR}/user/${file}" 2>/dev/null
 								${RMDIR} "${_VCSDIR}/user/${file}" 2>/dev/null
@@ -259,7 +262,9 @@ ADD)
 									;;
 								esac
 							}
-							merge_automerged () {
+
+							merge_automerged()
+								{
 								${ECHO} "Saving the currently installed revision to ${_VCSDIR}/automerged/${file}"
 								${MKDIR} -p "${_VCSDIR}/automerged/${file}" 2>/dev/null
 								${RMDIR} "${_VCSDIR}/automerged/${file}" 2>/dev/null
@@ -296,13 +301,14 @@ ADD)
 									;;
 								esac
 							}
-							if ${TEST} -f "${_VCSDIR}/automergedfiles" && ${GREP} -Fq "${file}" "${_VCSDIR}/automergedfiles"; then
+
+							if ${TEST} -f "${_VCSDIR}/automergedfiles" && ${GREP} -F "${file}" "${_VCSDIR}/automergedfiles" > /dev/null; then
 								#check if the automergedfile was manually edited after being automatically registered as merged
 								${TEST} ! -x ./+VERSIONING ||
 									./+VERSIONING CHECKOUT "${_VCSDIR}/automerged/${file}"
 								if ${TEST} -f "${_VCSDIR}/automerged/${file}"; then
 									${DIFF} -q "${file}" "${_VCSDIR}/automerged/${file}" 2>/dev/null
-									if ${TEST} ! $? -eq 0; then
+									if ${TEST} $? -ne 0; then
 										#the installed file and the last automerged version differ! must have been manually edited after being committed
 										${GREP} -Fv "${file}" "${_VCSDIR}/automergedfiles" > "${_VCSDIR}/automergedfiles.rm"
 										${MV} -f "${_VCSDIR}/automergedfiles.rm" "${_VCSDIR}/automergedfiles"
@@ -318,7 +324,7 @@ ADD)
 							fi
 						else
 						#always track installed conf files
-							if ! ${GREP} -Fq "${file}" "${_VCSDIR}/automergedfiles" 2>/dev/null; then
+							if ${GREP} -Fv "${file}" "${_VCSDIR}/automergedfiles" 2>/dev/null; then
 								${MKDIR} -p "${_VCSDIR}/user/${file}" 2>/dev/null;
 								${RMDIR} "${_VCSDIR}/user/${file}" 2>/dev/null;
 								${CP} -fp "${file}" "${_VCSDIR}/user/${file}";
@@ -330,10 +336,10 @@ ADD)
 							fi
 						fi
 					fi
-				elif ${TEST} -f "${f_eg}" -o -c "${f_eg}" \
-				&& ${TEST} "${_VCSCONFPULLFAIL}" = "yes" \
-				-o ! "${VCSCONFPULL}" = "yes" \
-				|| ${ECHO} "${f_flags}" | ${GREP} -Fq "r"; then
+				elif ( ${TEST} -f "${f_eg}" || ${TEST} -c "${f_eg}" ) \
+				&& ( ${TEST} "${_VCSCONFPULLFAIL}" = "yes" \
+				|| ${TEST} ! "${VCSCONFPULL}" = "yes" ) \
+				|| ${ECHO} "${f_flags}" | ${GREP} -F "r"; then
 					${ECHO} "${PKGNAME}: copying ${f_eg} to ${file}"
 					${CP} $f_eg $file
 					case $f_user in
@@ -388,7 +394,7 @@ REMOVE)
 			"")
 				if ${TEST} -f "$preexist"; then
 					:
-				elif ${TEST} -f "$file" -a \( -f "$f_eg" -o -c "$f_eg" \) && \
+				elif ${TEST} -f "${file}" && ( ${TEST} -f "${f_eg}" || ${TEST} -c "${f_eg}" ) && \
 				     ${CMP} -s "$file" "$f_eg"; then
 					case "$f_flags:$_PKG_CONFIG:$_PKG_RCD_SCRIPTS" in
 					*f*:*:*|[!r]:yes:*|[!r][!r]:yes:*|[!r][!r][!r]:yes:*|*r*:yes:yes)
diff --git a/pkgtools/pkgconftrack/files/pkgconftrack b/pkgtools/pkgconftrack/files/pkgconftrack
--- a/pkgtools/pkgconftrack/files/pkgconftrack
+++ b/pkgtools/pkgconftrack/files/pkgconftrack
@@ -1,63 +1,69 @@
 #!/bin/sh
-usage () {
-	echo "Usage: pkgconftrack [-p PREFIX] [-m commit message]"\
+usage() {
+	echo 1>&2 "Usage: pkgconftrack [-p PREFIX] [-m commit message]"\
 	"store packagename [... packagenames]"
 }
+
 extractAdditionalFiles() {
 #TODO: parse files for includes
 }
+
 execute()
 {
 	if test "${USER}" = "root"; then
 		su -m pkgvcsconf -c "$1"
 		return $?
 	else
-		eval $1
+		eval "$1"
 		return $?
 	fi
 }
 
 pkgchown()
 {
-	_restoreDir="$(pwd)"
-	if ! echo "$1" | grep -Fq "${_VCSDIR}"; then
-		echo "path \"$1\" not under VCSDIR: \"${_VCSDIR}\""
+	_restoreDir="`pwd`"
+	if echo "${1}" | grep -Fv "${_VCSDIR}"; then
+		echo 1>&2 "path \"${1}\" not under VCSDIR: \"${_VCSDIR}\""
 		return 1
 	fi
 	if test -d "${_VCSDIR}"; then
 		chmod 700 "${_VCSDIR}"
 		chown pkgvcsconf:pkgvcsconf "${_VCSDIR}"
 	fi
-	if test -d "$1"; then
-		if test -n "$(find "$1" -perm -2000 -or -perm -4000 -print \
-			-quit 2>/dev/null)"; then
-			echo "SUID/SGID files under $1,"\ 
+	if test -d "${1}"; then
+		if test -n "`find "${1}" -perm -2000 -or -perm -4000 -print \
+			-quit 2>/dev/null`"; then
+			echo 1>&2 "SUID/SGID files under ${1},"\ 
 			"refusing to run CHOWN -R"
 		else
-			chmod 700 "$1"
-			chown -R pkgvcsconf:pkgvcsconf "$1"
+			chmod 700 "${1}"
+			chown -R pkgvcsconf:pkgvcsconf "${1}"
 		fi
-		if test "$1" = "${_VCSDIR}"; then
+		if test "${1}" = "${_VCSDIR}"; then
 			return 0
 		fi
 	fi
-	if test -f "$1"; then
-		if test -u "$1" -o -g "$1"; then
-			echo "SUID/SGID file at $1, refusing to chown it"
+	if test -f "${1}"; then
+		if test -u "${1}" || test -g "${1}"; then
+			echo 1>&2 "SUID/SGID file at ${1}, refusing to chown it"
 		else
-			chmod 600 "$1"
-			chown pkgvcsconf:pkgvcsconf "$1"
+			chmod 600 "${1}"
+			chown pkgvcsconf:pkgvcsconf "${1}"
 		fi
-		_dirs=$(dirname "$1")
+		_dirs="`dirname "${1}"`"
 	else
-		_dirs="$1"
+		_dirs="${1}"
 	fi
-	_dirsplit=$(echo "${_dirs}" | awk -F "${_VCSDIR}" '{print $2}'| tr "/" " " )
+	_dirsplit="`echo "${_dirs}" | awk -F "${_VCSDIR}" '{print $2}'| tr "/" " "`" 
 	cd "${_VCSDIR}"
 	for dir in ${_dirsplit}
 		do
 			if test -d "${dir}"; then
-					if ! execute "test -r \"${dir}\" -a -w \"${dir}\""; then 
+					execute "test -r \"${dir}\""
+					_canR=$?
+					execute "test -w \"${dir}\""
+					_canW=$?
+					if test "${_canR}" -ne 0 || test "${_canW}" -ne 0; then
 						chmod 700 "${dir}"
 						chown pkgvcsconf:pkgvcsconf\
 						"${dir}"
@@ -69,25 +75,26 @@ pkgchown()
 }
 
 if [ "${USER}" = "root" ]; then
-	drop=$(which true)
+	drop=`which true`
 else
-	drop=$(which false)
+	drop=`which false`
 fi
+
 store() {
-	if test ! -f $1; then
-		echo "Can't access file $1"
+	if test ! -f ${1}; then
+		echo 1>&2 "Can't access file ${1}"
 		return 1
 	fi
-	if test -d "$2" -a -w "$2"; then
-		if $drop; then
-			pkgchown "$2"
+	if test -d "${2}" && test -w "${2}"; then
+		if ${drop}; then
+			pkgchown "${2}"
 		fi
-		_dir=$(dirname $1)
+		_dir="`dirname ${1}`"
 		if [ ! -d "${2}/user/${_dir}" ]; then
 			execute "mkdir -p \"${2}/user/${_dir}\"";
 		fi
-		cp -f "$1" "${2}/user/${1}"
-		if $drop; then
+		cp -f "${1}" "${2}/user/${1}"
+		if ${drop}; then
 			pkgchown "${2}/user/${1}"
 		fi
 		case ${3} in
@@ -97,19 +104,20 @@ store() {
 				return $?
 				;;
 			"cvs")
-				if [ "$4" = "no" ]; then
+				if [ "${4}" = "no" ]; then
 					_CVSROOT="${2}/CVSROOT"
 				else
-					_CVSROOT="$4"
+					_CVSROOT="${4}"
 				fi
 				cd "${2}/user"
 				_status=0
+				_relPath="`echo "${1}" | sed 's@^/@@'`"
 				OLDIFS="$IFS"
 				IFS="/"
-				for curdir in $1
+				for curdir in ${_relPath} 
 					do
 						execute "cvs -d \"${_CVSROOT}\" add \"${curdir}\""
-						if [ ! $? -eq 0 ]; then
+						if [ $? -ne 0 ]; then
 							return 1
 						else
 							cd "${curdir}" 2>/dev/null
@@ -118,7 +126,7 @@ store() {
 				IFS="$OLDIFS"
 				;;
 			"git")
-				cd "$2"
+				cd "${2}"
 				execute "git --git-dir=\"${2}/.git\" --work-tree=\"${2}\" add -f \"${2}/user/${1}\""
 				return $?
 				;;
@@ -130,12 +138,13 @@ store() {
 			"subversion")
 				cd "${2}/user"
 				OLDIFS="$IFS"
+				_relPath="`echo "${1}" | sed 's@^/@@'`"
 				IFS="/"
 				_status=0
-				for curdir in $1
+				for curdir in ${_relPath}
 					do
 						execute "svn add --force --depth=empty \"${curdir}\""
-						if [ ! $? -eq 0 ]; then
+						if [ $? -ne 0 ]; then
 							return 1
 						else
 							cd "${curdir}" 2>/dev/null
@@ -144,34 +153,34 @@ store() {
 				IFS="$OLDIFS"
 				;;
 			*)
-				echo "Unsupported versioning system: $3"
+				echo 1>&2 "Unsupported versioning system: ${3}"
 				return 1
 				;;
 		esac		
 	else
-		echo "Can't use a working directory at VCSDIR: $2"
+		echo 1>&2 "Can't use a working directory at VCSDIR: ${2}"
 		return 1
 	fi
 	
 }
 
 commit() {
-	if test -d "$2" -a -w "$2"; then
-		cd "$2"
-		if $drop; then
-			pkgchown "$2"
+	if test -d "${2}" && test -w "${2}"; then
+		cd "${2}"
+		if ${drop}; then
+			pkgchown "${2}"
 		fi
-		_COMMITMESSAGE="$1"
-		case $3 in
+		_COMMITMESSAGE="${1}"
+		case ${3} in
 			"rcs")
 				#do nothing
 				return 0
 				;;
 			"cvs")
-				if [ "$4" = "no" ]; then
+				if [ "${4}" = "no" ]; then
 					_CVSROOT="${2}/CVSROOT"
 				else
-					_CVSROOT="$4"
+					_CVSROOT="${4}"
 				fi
 				execute "cvs -Q -d \"${_CVSROOT}\" commit -R -m \"${_COMMITMESSAGE}\""
 				return $?
@@ -179,7 +188,7 @@ commit() {
 			"git")
 				execute "git --git-dir=\"${2}/.git\" --work-tree=\"${2}\" commit -m \"${_COMMITMESSAGE}\""
 				_gitStatus=$?
-				if [ "$4" != "no" -a $_gitStatus -eq 0 ]; then
+				if [ "${4}" != "no" ] && [ $_gitStatus -eq 0 ]; then
 					execute "git --git-dir=\"${2}/.git\" --work-tree=\"${2}\" push origin master"
 					_gitStatus=$?
 				fi
@@ -188,7 +197,7 @@ commit() {
 			"mercurial")
 				execute "hg --repository \"${2}\" commit -m \"${_COMMITMESSAGE}\" --user pkgconftrack"
 				_hgStatus=$?
-				if [ "$4" != "no" -a $_hgStatus -eq 0 ]; then
+				if [ "${4}" != "no" ] && [ $_hgStatus -eq 0 ]; then
 					execute "hg --repository \"${2}\" push \"${4}\""
 					_hgStatus=$?
 				fi
@@ -200,56 +209,56 @@ commit() {
 				return $?
 				;;
 			*)
-				echo "pkgconfrack: commit: ${3}: unsupported VCS"
+				echo 1>&2 "pkgconfrack: commit: ${3}: unsupported VCS"
 				return 1
 				;;
 		esac
 	else
-		echo "Can't access VCSDIR at ${2}!"
+		echo 1>&2 "Can't access VCSDIR at ${2}!"
 		exit 1
 	fi
 }
 
-_toshift=0
 while getopts "p:m:" flag
 do
-	case $flag in
+	case ${flag} in
 	"m"|"M")
-		_MESSAGE=$OPTARG
-		_toshift=$((_toshift + 2))
+		_MESSAGE=${OPTARG}
 		;;
 	"p"|"P")
-		_PREFIX=$OPTARG
-		_toshift=$((_toshift +2))
+		_PREFIX=${OPTARG}
 		;;	
 	esac
 done
-shift $_toshift
-if [ -z "$_PREFIX" ]; then
+shift "`expr "${OPTIND}" - 1`"
+
+if [ -z "${_PREFIX}" ]; then
 	_PREFIX=/usr/pkg
 fi
-if [ -z "$_MESSAGE" ]; then
-	_MESSAGE=$(date)
+if [ -z "${_MESSAGE}" ]; then
+	_MESSAGE="`date`"
 fi
-tstamp=$(date +%s)
-_MESSAGE="${tstamp}:pkgconftrack: ${_MESSAGE}"
+_randId="`cat /dev/urandom | tr -dc '[0-9]' | fold -w 6 | head -n 1`"
+time="`date "+%Y%m%d%H%S"`"
+_MESSAGE="${tstamp}-${_randId}:pkgconftrack: ${_MESSAGE}"
 
-_VCSDIR="$VCSDIR"
-if [ -z "$_VCSDIR" ]; then
-	_VCSDIR=$(${_PREFIX}/sbin/pkg_admin config-var VCSDIR)
+_VCSDIR="${VCSDIR}"
+if [ -z "${_VCSDIR}" ]; then
+	_VCSDIR="`${_PREFIX}/sbin/pkg_admin config-var VCSDIR`"
 fi
-if [ -z "$_VCSDIR" ]; then
-	VARBASE=$(${_PREFIX}/sbin/pkg_info -i $(${_PREFIX}/sbin/pkg_info | head -n 1 | awk '{print $1}') | awk -F "=" '/^VARBASE=/ {gsub("\"","");printf "%s", $2}')
-	if [ -n "$VARBASE" ]; then
-		_VCSDIR=${VARBASE}/confrepo
+if [ -z "${_VCSDIR}" ]; then
+	_firstPackage="`${_PREFIX}/sbin/pkg_info | head -n 1 | awk '{print $1}' | awk -F "=" '/^VARBASE=/ {gsub("\"","");printf "%s", $2}'`"
+	VARBASE="`${_PREFIX}/sbin/pkg_info -i "${_firstPackage}"`"
+	if [ -n "${VARBASE}" ]; then
+		_VCSDIR="${VARBASE}/confrepo"
 	else
-		_VCSDIR=/var/confrepo
+		_VCSDIR="/var/confrepo"
 	fi
 fi
 
 _REMOTEVCS="$REMOTEVCS"
 if [ -z "$_REMOTEVCS" ]; then
-	_REMOTEVCS=$(${_PREFIX}/sbin/pkg_admin config-var REMOTEVCS)
+	_REMOTEVCS="`${_PREFIX}/sbin/pkg_admin config-var REMOTEVCS`"
 fi
 _REMOTEVCS="${_REMOTEVCS:-no}"
 case "${_REMOTEVCS}" in
@@ -260,7 +269,7 @@ esac
 
 _VCS="$VCS"
 if [ -z "$_VCS" ]; then
-	_VCS=$(${_PREFIX}/sbin/pkg_admin config-var VCS)
+	_VCS="`${_PREFIX}/sbin/pkg_admin config-var VCS`"
 fi
 _VCS="${_VCS:-rcs}"
 case "${_VCS}" in
@@ -302,41 +311,41 @@ store|STORE)
 	_status=0
 	for _PACKAGE in ${PACKAGES}
 		do
-			_pkgdbpath=$(${_PREFIX}/sbin/pkg_info -E "${_PACKAGE}")
+			_pkgdbpath="`${_PREFIX}/sbin/pkg_info -E "${_PACKAGE}"`"
 			if [ $? -eq 0 ]; then
 				echo "Storing configuration files for ${_PACKAGE}"
-				_LOCALBASE="$(${_PREFIX}/sbin/pkg_info -Q LOCALBASE "${_PACKAGE}")"
-				_filesList="$(${_PREFIX}/sbin/pkg_info -i "${_PACKAGE}" | awk -v pre="${_LOCALBASE}" '/^# FILE: / && $4 ~ /c/ && $4 !~ /r/ {printf "%s/%s\n", pre, $3}')"
+				_LOCALBASE="`${_PREFIX}/sbin/pkg_info -Q LOCALBASE "${_PACKAGE}"`"
+				_filesList="`${_PREFIX}/sbin/pkg_info -i "${_PACKAGE}" | awk -v pre="${_LOCALBASE}" '/^# FILE: / && $4 ~ /c/ && $4 !~ /r/ {printf "%s/%s\n", pre, $3}'`"
 				for file in ${_filesList}
 					do
 						extractAdditionalFiles "${file}"
 					done
-				_filesList="${_filesList} ${_includedFilesList}"
+				_filesList=""${_filesList}" "${_includedFilesList}""
 				for file in ${_filesList}
 					do
 						store "${file}" "${_VCSDIR}" "${_VCS}" "${_REMOTEVCS}"
-						if [ ! $? -eq 0 ]; then
+						if [ $? -ne 0 ]; then
 							_status=1
 						fi
 						if test -f "${_VCSDIR}/automergedfiles"\
-						&& grep -Fq "${file}" "${_VCSDIR}/automergedfiles"; then
+						&& grep -F "${file}" "${_VCSDIR}/automergedfiles" > /dev/null; then
 							grep -Fv "${file}" "${_VCSDIR}/automergedfiles" > "${_VCSDIR}/automergedfiles.rm"
 							mv -f "${_VCSDIR}/automergedfiles.rm" "${_VCSDIR}/automergedfiles"
 						fi
 					done
 			else
-				echo "Package not found:" "${_PACKAGE}" "in the pkgdb for" "${_PREFIX}"
+				echo 1>&2 "Package not found:" "${_PACKAGE}" "in the pkgdb for" "${_PREFIX}"
 			fi
 		done	
 		if [ $_status -eq 0 ]; then
 			commit "${_MESSAGE}" "${_VCSDIR}" "${_VCS}" "${_REMOTEVCS}"
 			exit $?
 		else
-			echo "Failed to store configuration files"
+			echo 1>&2 "Failed to store configuration files"
 		fi 
 	;;
 *)
-	echo "${ACTION}: unknown action"
+	echo 1>&2 "${ACTION}: unknown action"
 	usage
 	exit 2
 	;;
