mk/pkginstall: files: check if a configuration file has been manually modified after being automerged

diff --git a/mk/pkginstall/files b/mk/pkginstall/files
--- a/mk/pkginstall/files
+++ b/mk/pkginstall/files
@@ -179,7 +179,7 @@ ADD)
 						${CP} -fp "$f_eg" "$_VCSDIR/defaults/$file"
 						${TEST} ! -x ./+VERSIONING ||
 							./+VERSIONING REGISTER "$_VCSDIR/defaults/$file" 
-							${ECHO} REGISTER $_VCSDIR/defaults/$file
+							${ECHO} REGISTER "$_VCSDIR/defaults/$file"
 					else
 						${ECHO} "$_VCSDIR is not writable!"
 					fi	
@@ -188,40 +188,7 @@ ADD)
 					${ECHO} "${PKGNAME}: $file already exists"
 					if ${TEST} ! -n "$NOVCS" -a "$_PKG_RCD_SCRIPTS" = "no" -a "$VCSAUTOMERGE" = "yes" -a ! "$VCSCONFPULL" = "yes"; then
 						${ECHO} "${PKGNAME}: attempting to merge $file with new defaults!"
-						if ${TEST} -f "$_VCSDIR/automergedfiles" && ${TEST} $(${GREP} -c "$file" "$_VCSDIR/automergedfiles") -gt 0; then
-							${ECHO} "saving the currently installed revision to $_VCSDIR/automerged/$file"
-							${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
-							${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
-							${CP} -fp "$file" "$_VCSDIR/automerged/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING COMMIT "backup preexisting conf before attempting merge for $PKGNAME"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
-							${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
-							${TEST} ! -x ./+VERSIONING ||
-								./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file" 	
-							mergestatus=$?
-							case $mergestatus in
-							0)
-								${ECHO} "merged with no conflict. installing it to $file!"
-								${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
-								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
-								${TEST} -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
-								${ECHO} "revert from the last revision of $_VCSDIR/automerged/$file if needed"
-								;;
-							1)
-								${ECHO} "some conflicts merging. manually review them in"
-								${ECHO} "$_VCSDIR/defaults/$file.automerge"
-								${ECHO} "then copy the result to $file"
-								;;
-							*)
-								${ECHO} "merge exited with errors. not changing anything"		
-								;;
-							esac
-						else
+						merge_userinstalled() {
 							${ECHO} "saving the currently user-installed revision to $_VCSDIR/user/$file"
 							${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null
 							${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null
@@ -243,6 +210,11 @@ ADD)
 								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
 								if ${TEST} $? -eq 0; then
 									${ECHO} "$file" >> "$_VCSDIR/automergedfiles"
+									${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
+									${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
+									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+									${TEST} ! -x ./+VERSIONING ||
+										./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
 								fi
 								${TEST} ! -x ./+VERSIONING ||
 									./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
@@ -256,29 +228,85 @@ ADD)
 							*)
 								${ECHO} "merge exited with errors. not changing anything"
 								;;
-							esac	
-						fi	
+							esac
+						}
+						merge_automerged () {
+							${ECHO} "saving the currently installed revision to $_VCSDIR/automerged/$file"
+							${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
+							${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
+							${CP} -fp "$file" "$_VCSDIR/automerged/$file"
+							${TEST} ! -x ./+VERSIONING ||
+								./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
+							${TEST} ! -x ./+VERSIONING ||
+								./+VERSIONING COMMIT "backup preexisting conf before attempting merge for $PKGNAME"
+							${TEST} ! -x ./+VERSIONING ||
+								./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
+							${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
+							${TEST} ! -x ./+VERSIONING ||
+								./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
+							mergestatus=$?
+							case $mergestatus in
+							0)
+								${ECHO} "merged with no conflict. installing it to $file!"
+								${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
+								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+								${TEST} -x ./+VERSIONING ||
+									./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
+								${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+								${TEST} -x ./+VERSIONING ||
+									./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
+								${ECHO} "revert from the penultimate revision of $_VCSDIR/automerged/$file if needed"
+								;;
+							1)
+								${ECHO} "some conflicts merging. manually review them in"
+								${ECHO} "$_VCSDIR/defaults/$file.automerge"
+								${ECHO} "then copy the result to $file"
+								;;
+							*)
+								${ECHO} "merge exited with errors. not changing anything"
+								;;
+							esac
+						}
+						if ${TEST} -f "$_VCSDIR/automergedfiles" && ${TEST} $(${GREP} -c "$file" "$_VCSDIR/automergedfiles") -gt 0; then
+							#check if the automergedfile was manually edited after being automatically registered as merged
+							if ${TEST} -f "$_VCSDIR/automerged/$file"; then
+								${TEST} ! -x ./+VERSIONING ||
+									./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
+								${DIFF} -q "$file" "$_VCSDIR/automerged/$file" 2>/dev/null
+								if ${TEST} ! $? -eq 0; then
+									#the installed file and the last automerged version differ! must have been manually edited after being committed
+									${GREP} -v "$file" "$_VCSDIR/automergedfiles" > "$_VCSDIR/automergedfiles.rm"
+									${MV} -f "$_VCSDIR/automergedfiles.rm" "$_VCSDIR/automergedfiles"
+									merge_userinstalled
+								else
+									merge_automerged
+								fi
+							else
+								merge_automerged
+							fi
+						else
+							merge_userinstalled
+						fi
 					fi
-										
-				elif ${TEST} -f "$f_eg" -o -c "$f_eg" && ${TEST} "$CONFPULLFAIL" = "yes" -o ! "$VCSCONFPULL" = "yes" -o "$_PKG_RCD_SCRIPTS" = "yes"; then
-					${ECHO} "${PKGNAME}: copying $f_eg to $file"
-					${CP} $f_eg $file
-					case $f_user in
-					"")	;;
-					*)	${CHOWN} $f_user $file ;;
-					esac
-					case $f_group in
-					"")	;;
-					*)	${CHGRP} $f_group $file ;;
-					esac
-					case $f_mode in
-					"")	;;
-					*)	${CHMOD} $f_mode $file ;;
-					esac
-				fi
-				;;
+		elif ${TEST} -f "$f_eg" -o -c "$f_eg" && ${TEST} "$CONFPULLFAIL" = "yes" -o ! "$VCSCONFPULL" = "yes" -o "$_PKG_RCD_SCRIPTS" = "yes"; then
+			${ECHO} "${PKGNAME}: copying $f_eg to $file"
+			${CP} $f_eg $file
+			case $f_user in
+			"")	;;
+			*)	${CHOWN} $f_user $file ;;
+			esac
+			case $f_group in
+			"")	;;
+			*)	${CHGRP} $f_group $file ;;
+			esac
+			case $f_mode in
+			"")	;;
+			*)	${CHMOD} $f_mode $file ;;
 			esac
 		fi
+		;;
+	esac
+	fi
 	done
 	if ${TEST} ! -n "$NOVCS" -a ! "$VCSCONFPULL" = "yes"; then
 		${TEST} ! -x ./+VERSIONING ||
