mk/pkginstall/files: fixes after tidy up

diff --git a/mk/pkginstall/files b/mk/pkginstall/files
--- a/mk/pkginstall/files
+++ b/mk/pkginstall/files
@@ -118,6 +118,14 @@ case "${VCSCONFPULL}" in
 	VCSCONFPULL=yes
 	;;
 esac
+case "${VCSAUTOMERGE}" in
+[Yy][Ee][Ss])
+	VCSAUTOMERGE=yes
+	;;
+*)
+	VCSAUTOMERGE=no
+	;;
+esac
 exitcode=0
 
 case $ACTION in
@@ -162,89 +170,89 @@ ADD)
 		else
 			case "$f_flags:$_PKG_CONFIG:$_PKG_RCD_SCRIPTS" in
 			*f*:*:*|[!r]:yes:*|[!r][!r]:yes:*|[!r][!r][!r]:yes:*|*r*:yes:yes)
-				if ${TEST} "$_VCS_ENABLED" = "yes" \
-				&& ! ${ECHO} "$f_flags" | grep -Fq "r" \
-				&& ${TEST} ! "$VCSCONFPULL" = "yes"; then
-					if ${TEST} ! -d "$_VCSDIR"; then
-						#${RM} -f "$_VCSDIR" 
-						${MKDIR} -p "$_VCSDIR"
+				if ${TEST} "${_VCS_ENABLED}" = "yes" \
+				&& ! ${ECHO} "${f_flags}" | grep -Fq "r" \
+				&& ${TEST} ! "${VCSCONFPULL}" = "yes"; then
+					if ${TEST} ! -d "${_VCSDIR}"; then
+						${MKDIR} -p "${_VCSDIR}"
 						if ${TEST} ! $? -eq 0; then
 							_VCS_ENABLED=no
 						fi
 					fi
 					#drop privileges
-					if ${TEST} "$USER" = "root"; then
-						${CHOWN} pkgvcsconf:pkgvcsconf \						"$_VCSDIR"
+					if ${TEST} "${USER}" = "root"; then
+						${CHOWN} pkgvcsconf:pkgvcsconf\
+						"${_VCSDIR}"
 					fi
-					${CHMOD} 0700 "$_VCSDIR"		
+					${CHMOD} 0700 "${_VCSDIR}"		
 					for dir in "defaults" "automerged" "user"
 					do	
-						if ${TEST} ! -d "$_VCSDIR/$dir"; then
-							${RM} -f "$_VCSDIR/$dir"
-							${MKDIR} -p "$_VCSDIR/$dir"
+						if ${TEST} ! -d "${_VCSDIR}/${dir}"; then
+							${RM} -f "${_VCSDIR}/${dir}"
+							${MKDIR} -p "${_VCSDIR}/${dir}"
 						fi
 					done
 					${TEST} ! -x ./+VERSIONING ||
 						./+VERSIONING PREPARE
 					if ${TEST} ! $? -eq 0; then
-						${ECHO} "Failed to initialize the repository that should store configuration revisions at $_VCSDIR!"
+						${ECHO} "Failed to initialize the repository that should store configuration revisions at ${_VCSDIR}!"
 						${ECHO} "Temporarily disabling configuration files version tracking"
 						_VCS_ENABLED=no
 					fi
-					if ${TEST} -w "$_VCSDIR/defaults"; then
-						${MKDIR} -p "$_VCSDIR/defaults/$file" 2>/dev/null
-						${RMDIR} "$_VCSDIR/defaults/$file" 2>/dev/null
-						${CP} -fp "$f_eg" "$_VCSDIR/defaults/$file"
+					if ${TEST} -w "${_VCSDIR}/defaults"; then
+						${MKDIR} -p "${_VCSDIR}/defaults/${file}" 2>/dev/null
+						${RMDIR} "${_VCSDIR}/defaults/${file}" 2>/dev/null
+						${CP} -fp "${f_eg}" "${_VCSDIR}/defaults/${file}"
 						${TEST} ! -x ./+VERSIONING ||
-							./+VERSIONING REGISTER "$_VCSDIR/defaults/$file" 
-							${ECHO} REGISTER "$_VCSDIR/defaults/$file"
+							./+VERSIONING REGISTER "${_VCSDIR}/defaults/${file}" 
+							${ECHO} REGISTER "${_VCSDIR}/defaults/${file}"
 					else
-						${ECHO} "$_VCSDIR is not writable!"
+						${ECHO} "${_VCSDIR} is not writable!"
 					fi	
 				fi
-				if ${TEST} -f "$file"; then
-					${ECHO} "${PKGNAME}: $file already exists"
-					if ${TEST} "$_VCS_ENABLED" = "yes" \
-					-a ! "$VCSCONFPULL" = "yes"\
-					 && ! ${ECHO} "$f_flags" | ${GREP} -Fq "r"; then
-						if ${TEST} "$VCSAUTOMERGE" = "yes"; then
-							${ECHO} "${PKGNAME}: attempting to merge $file with new defaults!"
+				if ${TEST} -f "${file}"; then
+					${ECHO} "${PKGNAME}: ${file} already exists"
+					if ${TEST} "${_VCS_ENABLED}" = "yes" \
+					-a ! "${VCSCONFPULL}" = "yes"\
+					&& ! ${ECHO} "${f_flags}" | ${GREP} -Fq "r"; then
+						if ${TEST} "${VCSAUTOMERGE}" = "yes"; then
+							${ECHO} "${PKGNAME}: attempting to merge ${file} with new defaults!"
 							merge_userinstalled() {
-								${ECHO} "Saving the currently user-installed revision to $_VCSDIR/user/$file"
-								${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null
-								${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null
-								${CP} -fp "$file" "$_VCSDIR/user/$file"
+								${ECHO} "Saving the currently user-installed revision to ${_VCSDIR}/user/${file}"
+								${MKDIR} -p "${_VCSDIR}/user/${file}" 2>/dev/null
+								${RMDIR} "${_VCSDIR}/user/${file}" 2>/dev/null
+								${CP} -fp "${file}" "${_VCSDIR}/user/${file}"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING REGISTER "$_VCSDIR/user/$file"
+									./+VERSIONING REGISTER "${_VCSDIR}/user/${file}"
 								${TEST} ! -x ./+VERSIONING ||
 									./+VERSIONING COMMIT "backup user conf before attempting merge for $PKGNAME"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
-								${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
+									./+VERSIONING CHECKOUT-FIRST "${_VCSDIR}/defaults/${file}"
+								${CP} -fp "${file}" "${_VCSDIR}/defaults/${file}.automerge"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
+									./+VERSIONING MERGE "${f_eg}" "${_VCSDIR}/defaults/${file}"
 								mergestatus=$?
-								case $mergestatus in
+								case ${mergestatus} in
 								0)
-									${ECHO} "Merged with no conflicts. Installing the configuration to $file!"
-									${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
-									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+									${ECHO} "Merged with no conflicts. Installing the configuration to ${file}!"
+									${DIFF} -u "${file}" "${_VCSDIR}/defaults/${file}.automerge"
+									${CP} -fp "${_VCSDIR}/defaults/${file}.automerge" "${file}"
 									if ${TEST} $? -eq 0; then
-										${ECHO} "$file" >> "$_VCSDIR/automergedfiles"
-										${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
-										${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
-										${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+										${ECHO} "${file}" >> "${_VCSDIR}/automergedfiles"
+										${MKDIR} -p "${_VCSDIR}/automerged/${file}" 2>/dev/null
+										${RMDIR} "${_VCSDIR}/automerged/${file}" 2>/dev/null
+										${CP} -fp "${_VCSDIR}/defaults/${file}.automerge" "${_VCSDIR}/automerged/${file}"
 										${TEST} ! -x ./+VERSIONING ||
-											./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
+											./+VERSIONING REGISTER "${_VCSDIR}/automerged/${file}"
 									fi
 									${TEST} ! -x ./+VERSIONING ||
-										./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
-									${ECHO} "Revert from the last revision of $_VCSDIR/user/$file if needed"
+										./+VERSIONING CHECKOUT "${_VCSDIR}/defaults/${file}"
+									${ECHO} "Revert from the last revision of ${_VCSDIR}/user/${file} if needed"
 									;;
 								1)
 									${ECHO} "Some conflicts merging. Manually review them in"
-									${ECHO} "$_VCSDIR/defaults/$file.automerge"
-									${ECHO} "then copy the result to $file"
+									${ECHO} "${_VCSDIR}/defaults/${file}.automerge"
+									${ECHO} "then copy the result to ${file}"
 									;;
 								*)
 									${ECHO} "Merge exited with errors. Not changing anything"
@@ -252,52 +260,52 @@ ADD)
 								esac
 							}
 							merge_automerged () {
-								${ECHO} "Saving the currently installed revision to $_VCSDIR/automerged/$file"
-								${MKDIR} -p "$_VCSDIR/automerged/$file" 2>/dev/null
-								${RMDIR} "$_VCSDIR/automerged/$file" 2>/dev/null
-								${CP} -fp "$file" "$_VCSDIR/automerged/$file"
+								${ECHO} "Saving the currently installed revision to ${_VCSDIR}/automerged/${file}"
+								${MKDIR} -p "${_VCSDIR}/automerged/${file}" 2>/dev/null
+								${RMDIR} "${_VCSDIR}/automerged/${file}" 2>/dev/null
+								${CP} -fp "${file}" "${_VCSDIR}/automerged/${file}"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING REGISTER "$_VCSDIR/automerged/$file"
+									./+VERSIONING REGISTER "${_VCSDIR}/automerged/${file}"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING COMMIT "backup preexisting conf before attempting merge for $PKGNAME"
+									./+VERSIONING COMMIT "backup preexisting conf before attempting merge for ${PKGNAME}"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT-FIRST "$_VCSDIR/defaults/$file"
-								${CP} -fp "$file" "$_VCSDIR/defaults/$file.automerge"
+									./+VERSIONING CHECKOUT-FIRST "${_VCSDIR}/defaults/${file}"
+								${CP} -fp "${file}" "${_VCSDIR}/defaults/${file}.automerge"
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING MERGE "$f_eg" "$_VCSDIR/defaults/$file"
+									./+VERSIONING MERGE "${f_eg}" "${_VCSDIR}/defaults/${file}"
 								mergestatus=$?
-								case $mergestatus in
+								case ${mergestatus} in
 								0)
-									${ECHO} "Merged with no conflict. installing it to $file!"
-									${DIFF} -u "$file" "$_VCSDIR/defaults/$file.automerge"
-									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$file"
+									${ECHO} "Merged with no conflict. installing it to ${file}!"
+									${DIFF} -u "${file}" "${_VCSDIR}/defaults/${file}.automerge"
+									${CP} -fp "${_VCSDIR}/defaults/${file}.automerge" "${file}"
 									${TEST} -x ./+VERSIONING ||
-										./+VERSIONING CHECKOUT "$_VCSDIR/defaults/$file"
-									${CP} -fp "$_VCSDIR/defaults/$file.automerge" "$_VCSDIR/automerged/$file"
+										./+VERSIONING CHECKOUT "${_VCSDIR}/defaults/${file}"
+									${CP} -fp "${_VCSDIR}/defaults/${file}.automerge" "${_VCSDIR}/automerged/${file}"
 									${TEST} -x ./+VERSIONING ||
-										./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
-									${ECHO} "Revert from the penultimate revision of $_VCSDIR/automerged/$file if needed"
+										./+VERSIONING CHECKOUT "${_VCSDIR}/automerged/${file}"
+									${ECHO} "Revert from the penultimate revision of ${_VCSDIR}/automerged/${file} if needed"
 									;;
 								1)
 									${ECHO} "Some conflicts merging. manually review them in"
-									${ECHO} "$_VCSDIR/defaults/$file.automerge"
-									${ECHO} "then copy the result to $file"
+									${ECHO} "${_VCSDIR}/defaults/${file}.automerge"
+									${ECHO} "then copy the result to ${file}"
 									;;
 								*)
 									${ECHO} "Merge exited with errors. not changing anything"
 									;;
 								esac
 							}
-							if ${TEST} -f "$_VCSDIR/automergedfiles" && ${GREP} -Fq "$file" "$_VCSDIR/automergedfiles"; then
+							if ${TEST} -f "${_VCSDIR}/automergedfiles" && ${GREP} -Fq "${file}" "${_VCSDIR}/automergedfiles"; then
 								#check if the automergedfile was manually edited after being automatically registered as merged
 								${TEST} ! -x ./+VERSIONING ||
-									./+VERSIONING CHECKOUT "$_VCSDIR/automerged/$file"
-								if ${TEST} -f "$_VCSDIR/automerged/$file"; then
-									${DIFF} -q "$file" "$_VCSDIR/automerged/$file" 2>/dev/null
+									./+VERSIONING CHECKOUT "${_VCSDIR}/automerged/${file}"
+								if ${TEST} -f "${_VCSDIR}/automerged/${file}"; then
+									${DIFF} -q "${file}" "${_VCSDIR}/automerged/${file}" 2>/dev/null
 									if ${TEST} ! $? -eq 0; then
 										#the installed file and the last automerged version differ! must have been manually edited after being committed
-										${GREP} -Fv "$file" "$_VCSDIR/automergedfiles" > "$_VCSDIR/automergedfiles.rm"
-										${MV} -f "$_VCSDIR/automergedfiles.rm" "$_VCSDIR/automergedfiles"
+										${GREP} -Fv "${file}" "${_VCSDIR}/automergedfiles" > "${_VCSDIR}/automergedfiles.rm"
+										${MV} -f "${_VCSDIR}/automergedfiles.rm" "${_VCSDIR}/automergedfiles"
 										merge_userinstalled
 									else
 										merge_automerged
@@ -310,20 +318,23 @@ ADD)
 							fi
 						else
 						#always track installed conf files
-							if ! ${GREP} -Fq "$file" "$_VCSDIR/automergedfiles" 2>/dev/null; then
-								${MKDIR} -p "$_VCSDIR/user/$file" 2>/dev/null;
-								${RMDIR} "$_VCSDIR/user/$file" 2>/dev/null;
-								${CP} -fp "$file" "$_VCSDIR/user/$file";
+							if ! ${GREP} -Fq "${file}" "${_VCSDIR}/automergedfiles" 2>/dev/null; then
+								${MKDIR} -p "${_VCSDIR}/user/${file}" 2>/dev/null;
+								${RMDIR} "${_VCSDIR}/user/${file}" 2>/dev/null;
+								${CP} -fp "${file}" "${_VCSDIR}/user/${file}";
 								if ${TEST} $? -eq 0; then
 									${ECHO} "Attempting to track the existing configuration file"
 									${TEST} ! -x ./+VERSIONING ||
-										./+VERSIONING REGISTER "$_VCSDIR/user/$file"
+										./+VERSIONING REGISTER "${_VCSDIR}/user/${file}"
 								fi
 							fi
 						fi
 					fi
-				elif ${TEST} -f "$f_eg" -o -c "$f_eg" && ${TEST} "$_VCSCONFPULLFAIL" = "yes" -o ! "$VCSCONFPULL" = "yes" || ${ECHO} "$f_flags" | ${GREP} -Fq "r"; then
-					${ECHO} "${PKGNAME}: copying $f_eg to $file"
+				elif ${TEST} -f "${f_eg}" -o -c "${f_eg}" \
+				&& ${TEST} "${_VCSCONFPULLFAIL}" = "yes" \
+				-o ! "${VCSCONFPULL}" = "yes" \
+				|| ${ECHO} "${f_flags}" | ${GREP} -Fq "r"; then
+					${ECHO} "${PKGNAME}: copying ${f_eg} to ${file}"
 					${CP} $f_eg $file
 					case $f_user in
 					"")	;;
@@ -342,10 +353,10 @@ ADD)
 			esac
 		fi
 	done
-	if ${TEST} "$_VCS_ENABLED" = "yes" \
-	 && ${TEST} "$VCSCONFPULL" != "yes"; then
+	if ${TEST} "${_VCS_ENABLED}" = "yes" \
+	&& ${TEST} "${VCSCONFPULL}" != "yes"; then
 		${TEST} ! -x ./+VERSIONING ||
-			./+VERSIONING COMMIT "add $PKGNAME"
+			./+VERSIONING COMMIT "add ${PKGNAME}"
 	fi 
 	;;
 
